### ISSUE TITLE
[FR][MAP] Get rid of the default Leaflet styling

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/franchise#10]
Make geometries look CARTO style, using our default styling for Voyager basemap

**Comment by AbelVM** [comment]
As defined here:
```css
#layer['mapnik::geometry_type'=1] {
  marker-width: 7;
  marker-fill: #EE4D5A;
  marker-fill-opacity: 0.9;
  marker-line-color: #FFFFFF;
  marker-line-width: 1;
  marker-line-opacity: 1;
  marker-type: ellipse;
  marker-allow-overlap: true;
}
#layer['mapnik::geometry_type'=2] {
  line-color: #4CC8A3;
  line-width: 1.5;
  line-opacity: 1;
}
#layer['mapnik::geometry_type'=3] {
  polygon-fill: #826DBA;
  polygon-opacity: 0.9;
  ::outline {
    line-color: #FFFFFF;
    line-width: 1;
    line-opacity: 0.5;
  }
```
